from enum import StrEnum


class DocumentClassification(StrEnum):
    SINGLE_LINE_DIAGRAM = "SINGLE_LINE_DIAGRAM"
    ELECTRICAL_DRAWING = "ELECTRICAL_DRAWING"
    PANEL_SCHEDULE = "PANEL_SCHEDULE"
    EQUIPMENT_SCHEDULE = "EQUIPMENT_SCHEDULE"
    CABLE_SCHEDULE = "CABLE_SCHEDULE"
    TRANSFORMER_SHOP_DRAWING = "TRANSFORMER_SHOP_DRAWING"
    SWITCHGEAR_SHOP_DRAWING = "SWITCHGEAR_SHOP_DRAWING"
    BREAKER_DOCUMENT = "BREAKER_DOCUMENT"
    MOTOR_DATA = "MOTOR_DATA"
    FAULT_DATA = "FAULT_DATA"
    SPECIFICATION = "SPECIFICATION"
    EQUIPMENT_PHOTO = "EQUIPMENT_PHOTO"
    NAMEPLATE_PHOTO = "NAMEPLATE_PHOTO"
    STUDY_DOCUMENT = "STUDY_DOCUMENT"
    UNKNOWN = "UNKNOWN"
